#!/bin/bash --login
#$ -cwd
#$ -l nvidia_v100=2
#$ -t 1-27

module load apps/binapps/anaconda3/4.2.0
module load tools/env/proxy

source activate venv

cd /mnt/iusers01/gb01/mbaxrap7/scratch/breast_imaging_ML/training

python3 optuna_regression.py ${SGE_TASK_ID}
