#!/bin/bash --login

#SBATCH -p himem  # Partition is required. Runs on an Intel hardware.
                   # Or submit batch jobs to the "interactive" partition for AMD Genoa serial jobs.
#SBATCH -n 32
#SBATCH -t 7-0     # Wallclock limit (days-hours). Required!
                   # Max permitted is 7 days (7-0).

module load apps/binapps/anaconda3/4.2.0

source activate venv

cd /mnt/iusers01/gb01/mbaxrap7/scratch/breast_imaging_ML/data_processing

python3 preprocess_CRUK.py
