#!/bin/bash --login
#$ -cwd
#$ -l mem2000

module load apps/binapps/anaconda3/4.2.0
module load tools/env/proxy

source activate venv

cd /mnt/iusers01/gb01/mbaxrap7/scratch/breast_imaging_ML/data_processing

python3 dcm_processing.py
